title: Sensors
views:
  - path: default_view
    title: Sensors
    cards:
      - type: entities
        title: Device
        entities:
          - entity: sensor.inverter_model
          - entity: sensor.inverter_serial_no
      - type: entities
        title: Firmware
        entities:
          - entity: sensor.master_version
          - entity: sensor.slave_version
          - entity: sensor.manager_version
      - type: entities
        title: BMS 1
        entities:
          - entity: sensor.bms_1_version_code
          - entity: sensor.bms_1_slave_1_version_code
          - entity: sensor.bms_1_slave_2_version_code
          - entity: sensor.bms_1_slave_3_version_code
          - entity: sensor.bms_1_slave_4_version_code
          - entity: sensor.bms_1_slave_5_version_code
          - entity: sensor.bms_1_slave_6_version_code
          - entity: sensor.bms_1_slave_7_version_code
          - entity: sensor.bms_1_slave_8_version_code
          - entity: sensor.bms_1_temperature
          - entity: sensor.bms_1_soc
          - entity: sensor.bms_1_residual_energy
      - type: entities
        title: BMS 2
        entities:
          - entity: sensor.bms_2_version_code
          - entity: sensor.bms_2_slave_1_version_code
          - entity: sensor.bms_2_slave_2_version_code
          - entity: sensor.bms_2_slave_3_version_code
          - entity: sensor.bms_2_slave_4_version_code
          - entity: sensor.bms_2_slave_5_version_code
          - entity: sensor.bms_2_slave_6_version_code
          - entity: sensor.bms_2_slave_7_version_code
          - entity: sensor.bms_2_slave_8_version_code
          - entity: sensor.bms_2_temperature
          - entity: sensor.bms_2_soc
          - entity: sensor.bms_2_residual_energy
      - type: entities
        title: Meter 1
        entities:
          - entity: sensor.meter_1_connection_code
          - entity: sensor.meter_1_voltage_r
          - entity: sensor.meter_1_voltage_s
          - entity: sensor.meter_1_voltage_t
          - entity: sensor.meter_1_current_r
          - entity: sensor.meter_1_current_s
          - entity: sensor.meter_1_current_t
          - entity: sensor.meter_1_power_r
          - entity: sensor.meter_1_power_s
          - entity: sensor.meter_1_power_t
          - entity: sensor.meter_1_reactive_power
          - entity: sensor.meter_1_reactive_power_r
          - entity: sensor.meter_1_reactive_power_s
          - entity: sensor.meter_1_reactive_power_t
          - entity: sensor.meter_1_apparent_power
          - entity: sensor.meter_1_apparent_power_r
          - entity: sensor.meter_1_apparent_power_s
          - entity: sensor.meter_1_apparent_power_t
          - entity: sensor.meter_1_power_factor
          - entity: sensor.meter_1_power_factor_r
          - entity: sensor.meter_1_power_factor_s
          - entity: sensor.meter_1_power_factor_t
          - entity: sensor.meter_1_frequency
      - type: entities
        title: Meter 2
        entities:
          - entity: sensor.meter_2_connection_code
          - entity: sensor.meter_2_voltage_r
          - entity: sensor.meter_2_voltage_s
          - entity: sensor.meter_2_voltage_t
          - entity: sensor.meter_2_current_r
          - entity: sensor.meter_2_current_s
          - entity: sensor.meter_2_current_t
          - entity: sensor.meter_2_power
          - entity: sensor.meter_2_power_r
          - entity: sensor.meter_2_power_s
          - entity: sensor.meter_2_power_t
          - entity: sensor.meter_2_reactive_power
          - entity: sensor.meter_2_reactive_power_r
          - entity: sensor.meter_2_reactive_power_s
          - entity: sensor.meter_2_reactive_power_t
          - entity: sensor.meter_2_apparent_power
          - entity: sensor.meter_2_apparent_power_r
          - entity: sensor.meter_2_apparent_power_s
          - entity: sensor.meter_2_apparent_power_t
          - entity: sensor.meter_2_power_factor
          - entity: sensor.meter_2_power_factor_r
          - entity: sensor.meter_2_power_factor_s
          - entity: sensor.meter_2_power_factor_t
          - entity: sensor.meter_2_frequency
      - type: entities
        title: Status
        entities:
          - entity: sensor.protocol_version
          - entity: sensor.inverter_part_no
          - entity: sensor.inverter_model_id
          - entity: sensor.number_of_strings
          - entity: sensor.number_of_mppt
          - entity: sensor.rated_power
          - entity: sensor.max_active_power
          - entity: sensor.max_apparent_power
          - entity: sensor.max_reactive_export
          - entity: sensor.max_reactive_import
          - entity: sensor.status_1_code
          - entity: sensor.status_3_code
          - entity: sensor.alarm_1_code
          - entity: sensor.alarm_2_code
          - entity: sensor.alarm_3_code
      - type: entities
        title: PV Inputs
        entities:
          - entity: sensor.pv1_voltage
          - entity: sensor.pv1_current
          - entity: sensor.pv2_voltage
          - entity: sensor.pv2_current
          - entity: sensor.pv3_voltage
          - entity: sensor.pv3_current
          - entity: sensor.pv4_voltage
          - entity: sensor.pv4_current
          - entity: sensor.pv_power
      - type: entities
        title: Operation 1
        entities:
          - entity: sensor.voltage_r
          - entity: sensor.voltage_s
          - entity: sensor.voltage_t
          - entity: sensor.current_r
          - entity: sensor.current_s
          - entity: sensor.current_t
          - entity: sensor.active_power
          - entity: sensor.reactive_power
          - entity: sensor.power_factor
          - entity: sensor.grid_frequency
          - entity: sensor.inner_temperature
          - entity: sensor.bms_1_charge_power
          - entity: sensor.grid_power
      - type: entities
        title: EPS
        entities:
          - entity: sensor.eps_voltage_r
          - entity: sensor.eps_voltage_s
          - entity: sensor.eps_voltage_t
          - entity: sensor.eps_current_r
          - entity: sensor.eps_current_s
          - entity: sensor.eps_current_t
          - entity: sensor.eps_power_r
          - entity: sensor.eps_power_s
          - entity: sensor.eps_power_t
          - entity: sensor.eps_power
          - entity: sensor.eps_frequency
      - type: entities
        title: Operation 2
        entities:
          - entity: sensor.load_power_r
          - entity: sensor.load_power_s
          - entity: sensor.load_power_t
          - entity: sensor.load_power
          - entity: sensor.battery_voltage
          - entity: sensor.battery_current
          - entity: sensor.bms_1_power
          - entity: sensor.bms_2_voltage
          - entity: sensor.bms_2_current
          - entity: sensor.bms_2_power
          - entity: sensor.battery_power
          - entity: sensor.active_power_r
          - entity: sensor.active_power_s
          - entity: sensor.active_power_t
          - entity: sensor.reactive_power_r
          - entity: sensor.reactive_power_s
          - entity: sensor.reactive_power_t
          - entity: sensor.apparent_power_r
          - entity: sensor.apparent_power_s
          - entity: sensor.apparent_power_t
          - entity: sensor.apparent_power
          - entity: sensor.frequency_r
          - entity: sensor.frequency_s
          - entity: sensor.eps_frequency_t
          - entity: sensor.available_import_power
          - entity: sensor.available_export_power
          - entity: sensor.pv1_power
          - entity: sensor.pv2_power
          - entity: sensor.pv3_power
          - entity: sensor.pv4_power
      - type: entities
        title: Utility Meters
        entities:
          - entity: sensor.pv_energy_total
          - entity: sensor.pv_energy_today
          - entity: sensor.charge_energy_total
          - entity: sensor.charge_energy_today
          - entity: sensor.discharge_energy_total
          - entity: sensor.discharge_energy_today
          - entity: sensor.feed_in_energy_total
          - entity: sensor.feed_in_energy_today
          - entity: sensor.grid_consumption_energy_total
          - entity: sensor.grid_consumption_energy_today
          - entity: sensor.output_energy_total
          - entity: sensor.output_energy_today
          - entity: sensor.input_energy_total
          - entity: sensor.input_energy_today
          - entity: sensor.load_energy_total
          - entity: sensor.load_energy_today
      - type: entities
        title: Remote Control
        entities:
          - entity: sensor.remote_control
          - entity: sensor.remote_timeout_set
          - entity: sensor.remote_control_active_power_command
          - entity: sensor.remote_control_reactive_power_command
          - entity: sensor.remote_timeout_countdown
          - entity: sensor.pwr_limit_bat_up
          - entity: sensor.pwr_limit_bat_dn
      - type: entities
        title: Charge Times
        entities:
          - entity: sensor.import_power_limit
          - entity: sensor.threshold_soc
          - entity: sensor.export_peak_limit
          - entity: sensor.charge_from_grid
          - entity: sensor.time_period_1_start_hour
          - entity: sensor.time_period_1_start_minute
          - entity: sensor.time_period_1_end_hour
          - entity: sensor.time_period_1_end_minute
          - entity: sensor.time_period_2_start_hour
          - entity: sensor.time_period_2_start_minute
          - entity: sensor.time_period_2_end_hour
          - entity: sensor.time_period_2_end_minute
      - type: entities
        title: Settings
        entities:
          - entity: sensor.max_charge_current
          - entity: sensor.max_discharge_current
          - entity: sensor.min_soc
          - entity: sensor.max_soc
          - entity: sensor.min_soc_on_grid
          - entity: sensor.eps_frequency_code
          - entity: sensor.eps_enable
          - entity: sensor.balance_load
          - entity: sensor.balance_logic_first
          - entity: sensor.export_limit
          - entity: sensor.import_current_limit
          - entity: sensor.export_current_limit
          - entity: sensor.system_time
          - entity: sensor.power_compensation_PF
          - entity: sensor.power_compensation_QS
          - entity: sensor.active_power_derating
          - entity: sensor.power_on
          - entity: sensor.shut_down
          - entity: sensor.grid_safety_code
          - entity: sensor.grid_power_limit
          - entity: sensor.work_mode_code
          - entity: sensor.drm
          - entity: sensor.meter_1_code
          - entity: sensor.meter_2_code
          - entity: sensor.buzzer_code
          - entity: sensor.mppt_switch_code
          - entity: sensor.relay_1_switch_code
          - entity: sensor.relay_2_switch_code
          - entity: sensor.brightness_level
